Update migration

diff --git a/.github/workflows/acceptance.yml b/.github/workflows/acceptance.yml
--- a/.github/workflows/acceptance.yml
+++ b/.github/workflows/acceptance.yml
@@ -1,214 +1,302 @@
-name: hashicorp/go-discover/acceptance
+name: Acceptance
+
 on:
   push:
-    branches:
-      - master
+
+permissions:
+  contents: read
+
 env:
-  ALICLOUD_ACCESS_KEY: xxxxxxx
-  ALICLOUD_REGION: xxxxxxx
-  ALICLOUD_SECRET_KEY: xxxxxxx
-  ARM_CLIENT_ID: xxxxxxx
-  ARM_CLIENT_SECRET: xxxxxxx
-  ARM_ENVIRONMENT: xxxxxxx
-  ARM_SUBSCRIPTION_ID: xxxxxxx
-  ARM_TENANT_ID: xxxxxxx
-  AWS_ACCESS_KEY_ID: xxxxxxx
-  AWS_CLI_GPG_KEY: xxxxxxx
-  AWS_REGION: xxxxxxx
-  AWS_SECRET_ACCESS_KEY: xxxxxxx
-  DIGITALOCEAN_TOKEN: xxxxxxx
-  GOOGLE_CREDENTIALS: xxxxxxx
-  GOOGLE_PROJECT: xxxxxxx
-  GOOGLE_ZONE: xxxxxxx
-  PACKET_AUTH_TOKEN: xxxxxxx
-  PACKET_PROJECT: xxxxxxx
-  SCALEWAY_ORGANIZATION: xxxxxxx
-  SCW_ACCESS_KEY: xxxxxxx
-  SCW_DEFAULT_PROJECT_ID: xxxxxxx
-  SCW_SECRET_KEY: xxxxxxx
-  SERVICE_GO_DISCOVER_TESTS_ROLE_ARN: xxxxxxx
-  TENCENTCLOUD_SECRET_ID: xxxxxxx
-  TENCENTCLOUD_SECRET_KEY: xxxxxxx
-  TENCENT_REGION: xxxxxxx
-  TF_VAR_packet_project: xxxxxxx
-  TRITON_ACCOUNT: xxxxxxx
-  TRITON_KEY_ID: xxxxxxx
-  TRITON_URL: xxxxxxx
+  TEST_RESULTS: /tmp/test-results
+
 jobs:
-  go-test:
+  lint:
     runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
     steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
-      - name: restore_cache
-        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
         with:
-          key: go-mod-test-v1-{{ checksum "go.sum" }}
-          restore-keys: go-mod-test-v1-{{ checksum "go.sum" }}
-          path: "/go/pkg/mod"
-      - name: Run go tests
-        run: |-
-          mkdir -p /tmp/test-results
-          gotestsum -f standard-verbose --junitfile ${TEST_RESULTS}/results.xml .
-      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
-        with:
-          path: "/tmp/test-results"
+          go-version-file: go.mod
       - run: go mod download
       - name: Check go mod tidy
         run: |-
           go mod tidy
           git diff --exit-code
-  alicloud-provider:
-    if: # GitHub does not currently support regular expressions inside if conditions
-    #         github.ref != 'refs/heads//pull\/[0-9]+/'
+      - name: Check Formatting
+        run: |-
+          files=$(go fmt ./...)
+          if [ -n "$files" ]; then
+            echo "The following file(s) do not conform to go fmt:"
+            echo "$files"
+            exit 1
+          fi
+
+  go-test:
     runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
-    needs:
-      - go-test
+    strategy:
+      fail-fast: false
+      matrix:
+        go-version:
+          - '1.14' # oldest supported; named in go.mod
+          - 'oldstable'
+          - 'stable'
     steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
+        with:
+          go-version: ${{ matrix.go-version }}
+      - uses: autero1/action-gotestsum@2e48af62f5248bd3b014f598cd1aa69a01dd36e3 # v1.0.0
+        with:
+          gotestsum_version: 1.9.0
+
+      - name: Run go tests
+        run: |-
+          mkdir -p "$TEST_RESULTS"
+          gotestsum -f standard-verbose --junitfile "${TEST_RESULTS}/results.xml" .
+      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
+        with:
+          path: ${{ env.TEST_RESULTS }}
+          name: tests-linux
+
+  alicloud-provider:
+    # don't run on fork PRs
+    if: github.repository_owner == 'hashicorp'
+    runs-on: ubuntu-latest
+    needs:
+      - go-test
+    env:
+      ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
+      ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SECRET_KEY }}
+      # XXX
+      # ALICLOUD_REGION: xxx
+    steps:
+      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
+        with:
+          go-version: 'stable'
+      - uses: autero1/action-gotestsum@2e48af62f5248bd3b014f598cd1aa69a01dd36e3 # v1.0.0
+        with:
+          gotestsum_version: 1.9.0
+
       - uses: "./.github/actions/acctest"
         with:
           provider-test-infra-dir: aliyun
           provider-go-test-dir: aliyun
+
   aws-provider:
-    if: # GitHub does not currently support regular expressions inside if conditions
-    #         github.ref != 'refs/heads//pull\/[0-9]+/'
+    # don't run on fork PRs
+    if: github.repository_owner == 'hashicorp'
     runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
     needs:
       - go-test
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_REGION: ${{ vars.AWS_REGION }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
+        with:
+          go-version: 'stable'
+      - uses: autero1/action-gotestsum@2e48af62f5248bd3b014f598cd1aa69a01dd36e3 # v1.0.0
+        with:
+          gotestsum_version: 1.9.0
+
       - uses: "./.github/actions/acctest"
         with:
           provider-test-infra-dir: aws
           provider-go-test-dir: aws
+          aws-region: ${{ vars.AWS_REGION }}
+          aws-role-arn: ${{ secrets.SERVICE_GO_DISCOVER_TESTS_ROLE_ARN }}
+
   azure-vmss-provider:
-    if: # GitHub does not currently support regular expressions inside if conditions
-    #         github.ref != 'refs/heads//pull\/[0-9]+/'
+    # don't run on fork PRs
+    if: github.repository_owner == 'hashicorp'
     runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
     needs:
       - go-test
+    env:
+      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
+      ARM_ENVIRONMENT: ${{ vars.ARM_ENVIRONMENT }}
+      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
     steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
+        with:
+          go-version: 'stable'
+      - uses: autero1/action-gotestsum@2e48af62f5248bd3b014f598cd1aa69a01dd36e3 # v1.0.0
+        with:
+          gotestsum_version: 1.9.0
+
       - uses: "./.github/actions/acctest"
         with:
           provider-test-infra-dir: azure-vmss
           provider-go-test-dir: azure
           provider-go-test-tags: TestVmScaleSetAddrs
+
   azurerm-provider:
-    if: # GitHub does not currently support regular expressions inside if conditions
-    #         github.ref != 'refs/heads//pull\/[0-9]+/'
+    # don't run on fork PRs
+    if: github.repository_owner == 'hashicorp'
     runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
     needs:
       - go-test
+    env:
+      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
+      ARM_ENVIRONMENT: ${{ vars.ARM_ENVIRONMENT }}
+      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
     steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
+        with:
+          go-version: 'stable'
+      - uses: autero1/action-gotestsum@2e48af62f5248bd3b014f598cd1aa69a01dd36e3 # v1.0.0
+        with:
+          gotestsum_version: 1.9.0
+
       - uses: "./.github/actions/acctest"
         with:
           provider-test-infra-dir: azurerm
           provider-go-test-dir: azure
           provider-go-test-tags: TestTagAddrs
+
   digitalocean-provider:
-    if: # GitHub does not currently support regular expressions inside if conditions
-    #         github.ref != 'refs/heads//pull\/[0-9]+/'
+    # don't run on fork PRs
+    if: github.repository_owner == 'hashicorp'
     runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
     needs:
       - go-test
+    env:
+      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
     steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
+        with:
+          go-version: 'stable'
+      - uses: autero1/action-gotestsum@2e48af62f5248bd3b014f598cd1aa69a01dd36e3 # v1.0.0
+        with:
+          gotestsum_version: 1.9.0
+
       - uses: "./.github/actions/acctest"
         with:
           provider-test-infra-dir: digitalocean
           provider-go-test-dir: digitalocean
+
   gce-provider:
-    if: # GitHub does not currently support regular expressions inside if conditions
-    #         github.ref != 'refs/heads//pull\/[0-9]+/'
+    # don't run on fork PRs
+    if: github.repository_owner == 'hashicorp'
     runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
     needs:
       - go-test
+    env:
+      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
+      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
+      GOOGLE_ZONE: ${{ vars.GOOGLE_ZONE }}
     steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
+        with:
+          go-version: 'stable'
+      - uses: autero1/action-gotestsum@2e48af62f5248bd3b014f598cd1aa69a01dd36e3 # v1.0.0
+        with:
+          gotestsum_version: 1.9.0
+
       - uses: "./.github/actions/acctest"
         with:
           provider-test-infra-dir: gce
           provider-go-test-dir: gce
+
   k8s-provider:
-    if: # GitHub does not currently support regular expressions inside if conditions
-    #         github.ref != 'refs/heads//pull\/[0-9]+/'
+    # don't run on fork PRs
+    if: github.repository_owner == 'hashicorp'
     runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
     needs:
       - go-test
     steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
+        with:
+          go-version: 'stable'
+      - uses: autero1/action-gotestsum@2e48af62f5248bd3b014f598cd1aa69a01dd36e3 # v1.0.0
+        with:
+          gotestsum_version: 1.9.0
+
       - uses: "./.github/actions/acctest"
         with:
           provider-test-infra-dir: k8s
           provider-go-test-dir: k8s
           provider-tf-apply: terraform apply -target google_container_cluster.cluster -auto-approve && terraform apply -auto-approve
+
   packet-provider:
-    if: # GitHub does not currently support regular expressions inside if conditions
-    #         github.ref != 'refs/heads//pull\/[0-9]+/'
+    # don't run on fork PRs
+    if: github.repository_owner == 'hashicorp'
     runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
     needs:
       - go-test
+    env:
+      TF_VAR_packet_project: ${{ secrets.PACKET_PROJECT }}
+      PACKET_AUTH_TOKEN: ${{ secrets.PACKET_AUTH_TOKEN }}
+      PACKET_PROJECT: ${{ secrets.PACKET_PROJECT }}
     steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
+        with:
+          go-version: 'stable'
+      - uses: autero1/action-gotestsum@2e48af62f5248bd3b014f598cd1aa69a01dd36e3 # v1.0.0
+        with:
+          gotestsum_version: 1.9.0
+
       - uses: "./.github/actions/acctest"
         with:
           provider-test-infra-dir: packet
           provider-go-test-dir: packet
-  scaleway-provider:
-    if: # GitHub does not currently support regular expressions inside if conditions
-    #         github.ref != 'refs/heads//pull\/[0-9]+/'
-    runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
-    needs:
-      - go-test
-    steps:
-      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
-      - uses: "./.github/actions/acctest"
-        with:
-          provider-test-infra-dir: scaleway
-          provider-go-test-dir: scaleway
+
+## The account for using this provider is broken.  If we want to resume regression testing against this
+## provider, the account must be fixed or replaced (and creds added to repo or Vault).
+#  scaleway-provider:
+#    # don't run on fork PRs
+#    if: github.repository_owner == 'hashicorp'
+#    runs-on: ubuntu-latest
+#    needs:
+#      - go-test
+#    steps:
+#      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+#      - uses: "./.github/actions/acctest"
+#        with:
+#          provider-test-infra-dir: scaleway
+#          provider-go-test-dir: scaleway
+
   triton-provider:
-    if: # GitHub does not currently support regular expressions inside if conditions
-    #         github.ref != 'refs/heads//pull\/[0-9]+/'
+    # don't run on fork PRs
+    if: github.repository_owner == 'hashicorp'
     runs-on: ubuntu-latest
-    container:
-      image: docker.mirror.hashicorp.services/circleci/golang:1.13.15
     needs:
       - go-test
+    env:
+      TRITON_URL: ${{ vars.TRITON_URL }}
+      TRITON_ACCOUNT: ${{ secrets.TRITON_ACCOUNT }}
+      TRITON_KEY_ID: ${{ secrets.TRITON_KEY_ID }}
     steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
-      # Ensure parameter if_key_exists is set correctly
-      - name: Install SSH key
-        uses: shimataro/ssh-key-action@685d0f20da72e4b53cc81d373a2ed0a867770e46 # v2.5.1
+      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
         with:
-          key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
-          name: circle_ci_id_rsa
-          known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
-          if_key_exists: fail
+          go-version: 'stable'
+      - uses: autero1/action-gotestsum@2e48af62f5248bd3b014f598cd1aa69a01dd36e3 # v1.0.0
+        with:
+          gotestsum_version: 1.9.0
+
+      # Ensure parameter if_key_exists is set correctly
+      #- name: Install SSH key
+      #  uses: shimataro/ssh-key-action@685d0f20da72e4b53cc81d373a2ed0a867770e46 # v2.5.1
+      #  with:
+      #    key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
+      #    name: circle_ci_id_rsa
+      #    known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
+      #    if_key_exists: fail
       - uses: "./.github/actions/acctest"
         with:
           provider-test-infra-dir: triton
           provider-go-test-dir: triton
-permissions:
-  contents: read
